### ISSUE TITLE
Upload de gros fichiers non fonctionnel

### ISSUE THREAD

**Issue by fdubreil** [Geoplateforme/sdk-entrepot#23]
Testé en production GPF à partir de la branche sp18_gros_dl.

L'upload plante sur le premier fichier un peu gros (9 Go). Mais le fichier est bien déposé ...

Les données et la configuration utilisée sont disponibles sur le store-SVRP : /store/store-SVRP/arch-diff/private/fdubreil/PARCELLAIRE-EXPRESS/GPF

Ci-dessous le log :
```

FDubreil@DEL2202P078:~/Developpements/ignf-gpf-sdk$ python3 -m ignf_gpf_sdk --debug --ini config-recette_parcellaire.ini upload -f parcellaire-delivery.json
INFO - Création et complétion d'une livraison...
INFO - Création d'une livraison...
DEBUG - route_request(upload_list, GET, {'datastore': None}, {'name': 'PARCELLAIRE_EXPRESS_FRA-2307', 'page': 1, 'limit': 100})
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads, GET, {'name': 'PARCELLAIRE_EXPRESS_FRA-2307', 'page': 1, 'limit': 100}, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads, GET, {'name': 'PARCELLAIRE_EXPRESS_FRA-2307', 'page': 1, 'limit': 100}, None)
DEBUG - route_request(upload_create, POST, {'datastore': None}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads, POST, None, {'description': 'Parcellaire Express : édition de juillet 2023', 'name': 'PARCELLAIRE_EXPRESS_FRA-2307', 'srs': 'EPSG:4326', 'type': 'VECTOR'})
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads, POST, None, {'description': 'Parcellaire Express : édition de juillet 2023', 'name': 'PARCELLAIRE_EXPRESS_FRA-2307', 'srs': 'EPSG:4326', 'type': 'VECTOR'})
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 créée avec succès.
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : ajout des 1 tags...
DEBUG - route_request(upload_add_tags, POST, {'upload': '7f6e3961-d268-4544-b47a-093d75cf3b74', 'datastore': None}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/tags, POST, None, {'dpsg': 'dpsg2023-06-00107'})
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/tags, POST, None, {'dpsg': 'dpsg2023-06-00107'})
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : les 1 tags ont été ajoutés avec succès.
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : ajout des 0 commentaires...
DEBUG - route_request(upload_list_comment, GET, {'upload': '7f6e3961-d268-4544-b47a-093d75cf3b74', 'datastore': None}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/comments, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/comments, GET, None, None)
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : les 0 commentaires ont été ajoutés avec succès.
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : récupération de l'arborescence des données déjà téléversées...
DEBUG - route_request(upload_tree, GET, {'datastore': None, 'upload': '7f6e3961-d268-4544-b47a-093d75cf3b74'}, None)
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/tree, GET, None, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/tree, GET, None, None)
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : livraison de PARCELLAIRE_EXPRESS/arrondissement.gpkg...
DEBUG - route_request(upload_push_data, POST, {'datastore': None, 'upload': '7f6e3961-d268-4544-b47a-093d75cf3b74'}, {'path': 'PARCELLAIRE_EXPRESS'})
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data, POST, {'path': 'PARCELLAIRE_EXPRESS'}, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data, POST, {'path': 'PARCELLAIRE_EXPRESS'}, None)
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : livraison de PARCELLAIRE_EXPRESS/arrondissement.gpkg: terminé
INFO - Livraison PARCELLAIRE_EXPRESS_FRA-2307 : livraison de PARCELLAIRE_EXPRESS/borne_limite_propriete.gpkg...
DEBUG - route_request(upload_push_data, POST, {'datastore': None, 'upload': '7f6e3961-d268-4544-b47a-093d75cf3b74'}, {'path': 'PARCELLAIRE_EXPRESS'})
DEBUG - url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data, POST, {'path': 'PARCELLAIRE_EXPRESS'}, None)
DEBUG - __url_request(https://data.geopf.fr/api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data, POST, {'path': 'PARCELLAIRE_EXPRESS'}, None)
ALERTE - L'exécution d'une requête a échoué (tentative 1/1)... (ProxyError)
DEBUG - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/FDubreil/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.geopf.fr', port=443): Max retries exceeded with url: /api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/FDubreil/Developpements/ignf-gpf-sdk/ignf_gpf_sdk/io/ApiRequester.py", line 125, in url_request
    return self.__url_request(url, method, params=params, data=data, files=files)
  File "/home/FDubreil/Developpements/ignf-gpf-sdk/ignf_gpf_sdk/io/ApiRequester.py", line 211, in __url_request
    r = requests.request(**d_requests)
  File "/home/FDubreil/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/FDubreil/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/FDubreil/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/FDubreil/.local/lib/python3.10/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='data.geopf.fr', port=443): Max retries exceeded with url: /api/datastores/d753fef4-506d-42b1-9240-acbab9332e9a/uploads/7f6e3961-d268-4544-b47a-093d75cf3b74/data (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

ERREUR - L'exécution d'une requête a échoué après 1 tentatives.
ERREUR FATALE - L'exécution d'une requête a échoué après 1 tentatives.
```

**Comment by LudivineSchlegel** [comment]
Le problème ne viens pas de notre côté mais le l'infra de prod qui n'arréte pas de planté.
J'ai testé une livraison de 9Go hier ça passe pas tout les temps mais des fois ça fonctionne. Il faut faire un Jira

**Comment by LudivineSchlegel** [comment]
Bonjour @fdubreil 
La modification du SDK à été mise en prod hier. Il est maintenant possible de faire des livraisons de gros fichiers.
Si ça te conviens tu pourra fermé le ticket.
